### ISSUE TITLE
Exceptional::$host change.

### ISSUE THREAD

**Issue by snpy** [ankane/exceptional-php#10]
There seems to be a API `host` change; see: [publish docs](http://docs.getexceptional.com/api/publish/) at the bottom.

It was: `plugin.getexceptional.com`
.. and now it should be: `api.getexceptional.com`

**Comment by ankane** [comment]
Hey Marek,

Thanks for the notice. The official Ruby library uses `plugin.getexceptional.com` at the moment, so I think it's best to leave it as is.

https://github.com/exceptional/exceptional/blob/master/lib/exceptional/config.rb#L10

**Comment by snpy** [comment]
Thing is http://plugin.getexceptional.com/api/errors doesn't actually send errors; it returns 404 status.
Where http://api.getexceptional.com/api/errors gives 200 status and sends errors as expected.

**Comment by ankane** [comment]
I'm having trouble replicating the issue. Try double-checking your API key.

**Comment by snpy** [comment]
Sorry - my fault - I have updated some time ago /etc/hosts to prevent Exceptional reports plugin.
There's a lesson for me to try and `ping` at least domain before posting irrelevant issues :)

Sorry and thanks for nice work.

**Comment by ankane** [comment]
No worries. Glad you were able to solve it.
