### ISSUE TITLE
Pass $action/$controller regardless of HTTP_HOST

### ISSUE THREAD

**Issue by tjchambers** [ankane/exceptional-php#11]
I am using this fine package not only for the code that operates from my web server directly, but also for code under unit test and code that runs in the CLI as a background agent (triggered as a GEARMAN Worker). 

If I specify $controller and/or $action in this non-webserver based environment, because HTTP_HOST is not defined, exceptional-php skips passing my action/controller values. IMHO these should be sent to Exceptional regardless of the web context. I understand these are essentially crafted around the web MVC paradigm, but since they are useful outside that and beyond Rails for example, they should be passed if set.

**Comment by ankane** [comment]
Sounds good to me.

https://github.com/ankane/exceptional-php/commit/b3dba0a15be30373424d70d39d0ec32e841bd90b

**Comment by tjchambers** [comment]
I see you made this change, which seemed to be the same as I would do with one exception. You still perhaps chose to send them only if BOTH controller and action were filled in. Is this appropriate, or can they be sent if only one is used?

**Comment by ankane** [comment]
Since the API is ok with only one being set, might as well send it.

https://github.com/ankane/exceptional-php/commit/b27f2c9f7c24641cf6038ce05aa6bd030294655d
