### ISSUE TITLE
Add support for using exceptional behind a proxy

### ISSUE THREAD

**Issue by buzzedword** [ankane/exceptional-php#16]
Currently trying to work up my own version of this right now, but not really finding any good ways to do this. When an application is behind a proxy, exceptional fails to deliver messages. Trying to find a nice way to handle this.

**Comment by ankane** [comment]
Hey Daniel,

Sorry for the slow response!  I just saw this last night.  Commit 983d0344db0f24aa2be0c526b74a8e2acbea3e0b adds support for a proxy without authentication.

``` php
Exceptional::proxy($host, $port);
```

Hope this helps!

**Comment by buzzedword** [comment]
Anything regarding proxies with auth? That's the bigger one I'm facing right now. I'm currently rocking a curl-rewritten implementation of the lib to get that to work nicely, and its... slow. :(

**Comment by ankane** [comment]
cURL should be very fast.  I'd use it for this library if it wasn't an extension.

I don't have much time at the moment, but you're welcome to take a stab at it.

This is a great resource - http://www.ietf.org/rfc/rfc2616.txt and search for "Proxy-Authorization".
