### ISSUE TITLE
Please strip PHP_AUTH_PW from $_SERVER environment

### ISSUE THREAD

**Issue by pcheese** [ankane/exceptional-php#2]
In `ExceptionalEnvironment::to_array` you remove some keys and values from the $_SERVER . Please add PHP_AUTH_PW to the list of keys that are stripped to prevent HTTP Auth passwords from being sent to Exceptional. http://php.net/manual/en/features.http-auth.php

**Comment by ankane** [comment]
Definitely a good idea. Thanks.
