### ISSUE TITLE
Long Running Jobs cause accumulation without reporting

### ISSUE THREAD

**Issue by tjchambers** [ankane/exceptional-php#5]
I have a number of CLI jobs that run in the background and was having issues with the Exceptions not reported to getexceptional.com until the job was terminated. This caused memory expansion (duh!) and delays in the timestamps of the reporting relative to their true occurrence. 

I made a modification to the code to add a static method for flushing the exceptions list if any directly, so that I could at a convenient point (end of a task, etc.) flush the exceptions to the web and resume accumulating. 

This may be valuable to others.

**Comment by ankane** [comment]
I updated the library to send exceptions as they happen, so you don't have to worry about flushing them.

https://github.com/ankane/exceptional-php/commit/89695f853843fae2c4649260cdac963690ff9862

What do you think?
